### ISSUE TITLE
Pattern results, then... ?

### ISSUE THREAD

**Issue by Skip75** [map220v/DominationsGGScripts#1]
Can you please provide more details in readme ?Or better, add a menu choice :)
At first run of the script I get this :

![Capture](https://user-images.githubusercontent.com/44243520/114550803-e8b77f80-9c62-11eb-8424-2e3c8669ec6d.PNG)

At second run of script, nothing :

![notefound](https://user-images.githubusercontent.com/44243520/114550848-f2d97e00-9c62-11eb-924d-2ddac94988c2.PNG)

But anyway, I can't edit the values when searching manually: I find the values, but if I edit them, they directly revert to initial value... So A working script should help me 👍

**Comment by map220v** [comment]
After script executed It's should make: Resources(Gold, Food, Oil) for Crowns cost 0 and Speed Up(not working for buildings and university excluding forest) for Crowns cost 0
And this script disables game analytics so devs won't see that you purchased resources for 0 crowns frequently.

Also this game saves player and world data as json and sends to server like save file. And server doesn't seem to check that save file thats why this script works.

**Comment by Skip75** [comment]
thanks for explanation !
correct, working fine after first run of the script :)
So Gold, Oil and Food + Forest are now free of crown. Perfect, better than no mod at all 👍

**Comment by Skip75** [comment]
Hi @map220v is your script still working ? Today, when it reached the end of the script (100%) I had a pop-up "Illegal program detected (107/1)" then game crashed. Are you aware ?^^

**Comment by map220v** [comment]
I guess xigncode got update and now can detect process memory modifications on android. 
I don't know how to bypass anticheats.
